global using Model = EPAY.AIRWAY.KIOSK.API.Domain.Models;
global using EPAY.AIRWAY.KIOSK.API.Resources.SystemData;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Serilog;
global using EPAY.AIRWAY.KIOSK.API.Resources.Results;
global using EPAY.AIRWAY.KIOSK.API.Extensions;
global using AutoMapper;
global using EPAY.AIRWAY.KIOSK.API.Resources.Attributes;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Security.Claims;
global using MyEnum = EPAY.AIRWAY.KIOSK.API.Resources.Enums;